name: Run tests
on: [pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.4.4"
      - uses: leafo/gh-actions-luarocks@v4
      - name: build
        run: |
          luarocks init
          ./luarocks install --deps-only cautious-fiesta-scm-0.rockspec
          ./luarocks make
      - name: test
        run: |
          ./luarocks install luacov
          ./luarocks test
